added is-cli to documentation
iotaledger/integration-services pull request #561
Opened 2022-06-03 07:34 UTC by JuriBog

2022-06-03 07:53 UTC, mastrogiovanni requested changes

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is write-channel -i identityA.json -p "hello world" <Channel address of channelA>
Change `write-channel` implementation and docs to receive channel address from a channel file (the channelA.json of the previous example). The command write-channel need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is subscribe-channel -i identityB.json <Channel address of channelA>
The command subscribe-channel need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the last parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is authorize-channel -i identityA.json <Channel address of channelA> <Id of identityB>
The command authorize-channel need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is write-channel -i identityB.json -p "Can you hear me?" <Channel address of channelA>
The command write-channel need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is read-channel -i identityB.json <Channel address of channelA>
The command read-channel need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is read-channel-history -i identityB.json -psK <preshared key> <Channel address of channelA>
The command read-channel-history need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +The user can also read the history of a Channel. Especially if the Channel is `public` it is the only way for the subscriber to read the Channel. For that add the option `-pC` and remove the option f
Split that in two different example:
Read history of a public Channel
Read history of a private Channel

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is revoke-subscription -i identityA.json -sI <Id of identityB> <Channel address of channelA>
The command revoke-subscription need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-03 07:53 UTC, mastrogiovanni commented on documentation/docs/is-cli/is_cli_examples.md
> +is find-subscription -i identityA.json -sI <Id of identityB> <Channel address of channelA>
The command find-subscription need to have a -c channelFile.json where read the channel address. In this way we avoid complex copy and paste. Remove channel address as the parameter

2022-06-05 13:46 UTC, Schereo commented
Just a general feeling of mine. I think it would be better to combine both pages into one. Less pages are better imo.

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/introduction.md
> +### Configure CLI for local API access
Maybe also add the command for configuring the CLI for usage with a single url.

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/introduction.md
> +### Configure API environment
I would really add a little more description here. For example that this command is used for setting up the API's environment with node but only need once.
Also maybe add the other command `is setup-docker` for setting up the environment for docker.

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +In this example we will show how to create Identities, Channels and how to subscribe to a channel, authorize one Subscriber and write data into a Channel.
```suggestion
In this example we will show how to create Identities, Channels and how to subscribe to a channel, authorize a Subscriber and write data into a Channel.
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +First create two files `identityA.json` and `identitiyB.json` for creating these Identities with the CLI in the next step. Rename for the second file the `username`.
```suggestion
First create two files `identityA.json` and `identitiyB.json` for creating these Identities with the CLI in the next step. Rename the `username` field in `identityB.json` into `actorB`.
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +Other users need first to subscribe to a Channel.
```suggestion
Other users need to subscribe to a Channel first.
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +The creator of the Channel authorize one subscriber.
```suggestion
The creator of the Channel authorizes a subscriber.
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +### Write message as a subscriber
```suggestion
### Write Message as a Subscriber
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +The subscriber can read the Channel entries but just only the ones after he was authorized to the Channel.
```suggestion
The subscriber can read the Channel entries but only ones created after he/she was authorized to the Channel.
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +### Read history of Channel
```suggestion
### Read History of Channel
```

2022-06-05 13:58 UTC, Schereo commented on documentation/docs/is-cli/is_cli_examples.md
> +### Find subscription
```suggestion
### Find Subscription
```

2022-06-16 10:12 UTC, Schereo approved these changes

2022-06-16 12:20 UTC, mastrogiovanni approved these changes

2022-06-16 12:20 UTC, merged